name: Destroy Resources

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: '.'

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: infra/

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/

      - name: Terraform Plan (Destroy)
        run: terraform plan -destroy -out=tfplan
        working-directory: infra/

      - name: Terraform Apply (Destroy)
        run: terraform apply -auto-approve tfplan
        working-directory: infra/
